name: Génération et publication de la documentation 

on:
  push:
    branches:
      - main  # Exécute le workflow uniquement sur la branche main
    paths:
      - spec.yaml  # Limite l'exécution aux modifications de spec.yaml
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilise GITHUB_TOKEN pour les actions de commit/push
          fetch-depth: 0  # Récupère tout l'historique pour permettre les commits

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Vérification de la syntaxe
        run: redocly lint spec.yaml --format=github-actions
        
      - name: Génération de la documentation
        run: redocly build-docs spec.yaml -o ./docs/index.html

      - name: Mise en ligne de la documentation
        run: |
          git add docs/index.html
          git commit -m "Mise à jour de la documentation API"
          git push origin main
