name: Génération et publication de la documentation 
on:
  push:
    branches:
      - main  # Exécute le workflow uniquement sur la branche main
    paths:
      - spec.yaml  # Limite l'exécution aux modifications de spec.yaml
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Generate API documentation
        run: redocly build-docs spec.yaml -o ./docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
